model:
  name: "SimpleClassifier"
  type: "Sequential"
  layers:
    - type: "Linear"
      input_size: 784
      output_size: 128
      activation: "ReLU"
    - type: "Dropout"
      p: 0.2
    - type: "Linear"
      input_size: 128
      output_size: 10
      activation: "Softmax"
  optimizer:
    type: "Adam"
    learning_rate: 0.001
  loss: "CrossEntropyLoss"
  metrics: ["accuracy"]

training:
  epochs: 5
  batch_size: 32
  validation_split: 0.2